---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/cron

namespace: "calibre-auto-import"
namePrefix: "calibre-auto-import-"
images:
  - name: "mattcl/calibre-auto-import"
    newTag: "0.2.0"

configMapGenerator:
  - name: job-config
    envs:
      - "job-config.env"
