---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: traefik-internal
  labels:
    traffic-type: internal
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`calibre-auto-import.hl.ancalagon.black`)
      priority: 10
      services:
        - name: calibre-auto-import-svc
          port: 80
  tls:
    certResolver: default
